import type { Metadata } from "next";
import { Geist, Geist_Mono, GFS_Didot } from "next/font/google";
import "./globals.css";
import { NavbarComponent } from "@/components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const gfsDidot = GFS_Didot({
  variable: "--font-gfs-didot",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${gfsDidot.variable} antialiased`}
      >
        <NavbarComponent/>
        {children}
      </body>
    </html>
  );
}
